name: Build & Upload Android Release

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    name: Build Android Release APK
    runs-on: ubuntu-latest

    env:
      APP_ID: com.vega
      VERSION_NAME: 3.1.1
      VERSION_CODE: 311
      MYAPP_UPLOAD_STORE_FILE: release.keystore
      MYAPP_UPLOAD_KEY_ALIAS: ${{ secrets.MYAPP_UPLOAD_KEY_ALIAS }}
      MYAPP_UPLOAD_STORE_PASSWORD: ${{ secrets.MYAPP_UPLOAD_STORE_PASSWORD }}
      MYAPP_UPLOAD_KEY_PASSWORD: ${{ secrets.MYAPP_UPLOAD_KEY_PASSWORD }}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: 17

      - name: Install Dependencies
        run: yarn install

      - name: Fix NativeWind async PostCSS plugin error
        run: |
          echo "Patching NativeWind extract-styles.js..."
          FILE="node_modules/nativewind/dist/postcss/extract-styles.js"
          echo 'module.exports = async function extractStyles(css, cb) { return cb(await processor.process(css)) }' > "$FILE"

      - name: Decode Keystore from Secret
        run: |
          echo "${{ secrets.MYAPP_UPLOAD_STORE_BASE64 }}" | base64 -d > android/app/${MYAPP_UPLOAD_STORE_FILE}

      - name: Build Release APK
        run: |
          cd android
          ./gradlew assembleRelease

      - name: Upload APK Artifact
        uses: actions/upload-artifact@v4
        with:
          name: release-apk
          path: android/app/build/outputs/apk/release/app-release.apk
