name: Build & Upload Android Debug APK

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    name: Build Android Debug APK
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: 17

      - name: Install Dependencies
        run: yarn install

      - name: Fix NativeWind async PostCSS plugin error
        run: |
          echo "Fixing NativeWind async extractStyles"
          FILE="node_modules/nativewind/dist/postcss/extract-styles.js"
          echo "module.exports.extractStyles = async function(css, cb) { return cb(await processor.process(css)) };" > $FILE

      - name: Configure Gradle Memory
        run: |
          GRADLE_PROPS=android/gradle.properties
          sed -i 's|^org.gradle.jvmargs=.*|org.gradle.jvmargs=-Xmx6g -XX:MaxMetaspaceSize=1g|' "$GRADLE_PROPS"

      - name: Make gradlew executable
        run: chmod +x android/gradlew

      - name: Build Debug APK
        run: |
          cd android
          ./gradlew clean
          ./gradlew assembleDebug

      - name: Rename APK with Timestamp
        run: |
          cd android
          mkdir -p ../release
          cp app/build/outputs/apk/debug/app-debug.apk ../release/Vega-debug-$(date +%Y%m%d%H%M).apk

      - name: Upload Debug APK Artifact
        uses: actions/upload-artifact@v4
        with:
          name: debug-apk
          path: release/*.apk
